/*
 * rest-api
 * An api to fetch manipulate and enter data to the Local Admin service. All Responses can be done with JSON and XML where JSON is the default. You can change the response by setting the content-type header. The downside of our XML is that we do not provide XLS for the Responses
 *
 * OpenAPI spec version: 1.1.0
 * Contact: nbrugger@student.tgm.ac.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.localadmin.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.localadmin.model.Paths1authgetresponses401contentapplication1jsonschemapropertiescode;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
import javax.xml.bind.annotation.*;
/**
 * Describing the error
 */
@Schema(description = "Describing the error")
@XmlRootElement(name = "ErrorResponse1")
@XmlAccessorType(XmlAccessType.FIELD)

public class ErrorResponse1 implements Serializable{
  private static final long serialVersionUID = 1L;
  @XmlElement(name = "message")
  @SerializedName("message")
  private String message = "Unknown Fail";

  @XmlElement(name = "code")
  @SerializedName("code")
  private Paths1authgetresponses401contentapplication1jsonschemapropertiescode code = null;

  public ErrorResponse1 message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Describes what went wrong human readable
   * @return message
  **/
  @Schema(required = true, description = "Describes what went wrong human readable")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ErrorResponse1 code(Paths1authgetresponses401contentapplication1jsonschemapropertiescode code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public Paths1authgetresponses401contentapplication1jsonschemapropertiescode getCode() {
    return code;
  }

  public void setCode(Paths1authgetresponses401contentapplication1jsonschemapropertiescode code) {
    this.code = code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponse1 errorResponse1 = (ErrorResponse1) o;
    return Objects.equals(this.message, errorResponse1.message) &&
        Objects.equals(this.code, errorResponse1.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, code);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponse1 {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
