/*
 * rest-api
 * An api to fetch manipulate and enter data to the Local Admin service. All Responses can be done with JSON and XML where JSON is the default. You can change the response by setting the content-type header. The downside of our XML is that we do not provide XLS for the Responses
 *
 * OpenAPI spec version: 1.1.0
 * Contact: nbrugger@student.tgm.ac.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.localadmin.api;

import com.localadmin.ApiException;
import com.localadmin.model.InlineResponse200;
import com.localadmin.model.InlineResponse2001;
import com.localadmin.model.Paths1filter17Bname7D1columnsgetresponses200contentapplication1jsonschemaitems;
import com.localadmin.model.Paths1restaurantsgetresponses401contentapplication1jsonschema;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ColumnApi
 */
@Ignore
public class ColumnApiTest {

    private final ColumnApi api = new ColumnApi();

    /**
     * Get All Columns
     *
     * Gets all columns (dailycolumn, dailyformula, salarylevel)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllColumnsTest() throws ApiException {
        List<Paths1filter17Bname7D1columnsgetresponses200contentapplication1jsonschemaitems> response = api.getAllColumns();

        // TODO: test validations
    }
    /**
     * Get Typeof Column
     *
     * Gets the type of the column
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getColumnTypeTest() throws ApiException {
        String name = null;
        InlineResponse200 response = api.getColumnType(name);

        // TODO: test validations
    }
    /**
     * Is Column in Use
     *
     * Tells if the column in use or not
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isColumnInUseTest() throws ApiException {
        String name = null;
        InlineResponse2001 response = api.isColumnInUse(name);

        // TODO: test validations
    }
}
