/*
 * rest-api
 * An api to fetch manipulate and enter data to the Local Admin service. All Responses can be done with JSON and XML where JSON is the default. You can change the response by setting the content-type header. The downside of our XML is that we do not provide XLS for the Responses
 *
 * OpenAPI spec version: 1.1.0
 * Contact: nbrugger@student.tgm.ac.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.localadmin.api;

import com.localadmin.ApiClient;
import com.localadmin.ApiException;
import com.localadmin.Configuration;
import com.localadmin.auth.ApiKeyAuth;
import com.localadmin.model.Apikeywrapper;
import com.localadmin.model.ColumnType;
import com.localadmin.model.ColumnUse;
import com.localadmin.model.ErrorResponse;
import com.localadmin.model.InlineResponse200;
import com.localadmin.model.InlineResponse2001;
import com.localadmin.model.Restaurant;
import com.localadmin.model.SalaryChange;
import com.localadmin.model.SalaryChange1;

import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ColumnApi
 */
public class ColumnApiTest {

	private final ColumnApi api = new ColumnApi();
	private final DailycolumnApi dailycolumApi = new DailycolumnApi();
	private final FormulasApi formulaApi = new FormulasApi();
	private final PayrollApi payrollApi = new PayrollApi();
	private ApiKeyAuth User_Auth;
	private String key;
	private boolean resetColumnTableBefore = false; // should it clear the table for each Test so if one fails the
														// others does not fail

	@Before
	public void setup() {
		ApiClient defaultClient = Configuration.getDefaultApiClient();

		UsersApi usersApi = new UsersApi();
		try {
			Apikeywrapper wrapper = usersApi.authenticate("admin@kingrestaurants.at", "12345678");
			key = wrapper.getKey();
		} catch (ApiException e) {
			fail("Login failed from Admin");
		}

		// Configure API key authorization: User_Auth
		User_Auth = (ApiKeyAuth) defaultClient.getAuthentication("User_Auth");
		User_Auth.setApiKey(key);

		if (resetColumnTableBefore) {
			try {
				dailycolumApi.deleteAllDailycolumns();
				formulaApi.deleteAllDailyformulas();
			} catch (ApiException e) {
				fail("Fail when reseting column table! " + e.getCode());
			}
		}
	}

	/**
	 * Get All Columns, TypeOf Column, IsInUse Column
	 *
	 * Tests all 3 operations of Column
	 *
	 * @throws ApiException
	 *             if the Api call fails
	 */
	@Test
	public void ColumnGetTypeUseTest() throws ApiException {

		Dailycolumn dailycolumn1 = new Dailycolumn();
		dailycolumn1.setName("dailyColumn1");
		dailycolumn1.setHide(false);

		DailyFormulas dailyformulas1 = new DailyFormulas();
		dailyformulas1.setName("dailyFormula1");
		dailyformulas1.setPercent(true);
		dailyformulas1.setValue1("1");
		dailyformulas1.setValue1("5");

		// Add column from type DailyColumn which should not work
		try {
			dailycolumApi.addDailycolumn(dailycolumn1);
			fail("Was able to add DailyColumn even tough its not setup with all values yet!");
		} catch (ApiException e) {
		}

		// Add column from type DailyFormula which should not work
		try {
			formulaApi.addDailyformula(dailyformulas1);
			fail("Was able to add SalaryLevel even tough its not setup with all values yet!");
		} catch (ApiException e) {
		}

		dailyformulas1.setOperator(Dailyoperators.ADD);
		dailycolumn1.setDescription("A column");

		// Add column from type DailyColumn
		try {
			dailycolumApi.addDailycolumn(dailycolumn1);
		} catch (ApiException e) {
			fail("Error when adding DailyColumn!");
		}

		// Add column from type DailyFormula
		try {
			formulaApi.addDailyformula(dailyformulas1);
		} catch (ApiException e) {
			fail("Error when adding DailyFormula!");
		}

		// Add column from type SalaryLevel
		try {
			payrollApi.addSalaryLevel("LevelXYZ");
		} catch (ApiException e) {
			fail("Error when adding SalaryChange!");
		}

		// Get all columns
		try {
			List<String> columnNames = api.getAllColumns();
			assertEquals("There should be 3 columns!", 2, columnNames.size());
			assertEquals("Name of Column at 0 is wrong!", dailycolumn1.getName(), columnNames.get(0));
			assertEquals("Name of Column at 1 is wrong!", dailyformulas1.getName(), columnNames.get(1));
			assertEquals("Name of Column at 2 is wrong!", "LevelXYZ", columnNames.get(2));
		} catch (ApiException e) {
			fail("Error when getting Columns!");
		}

		// Type Of the columns
		try {
			ColumnType type = api.getColumnType(dailycolumn1.getName());
			assertEquals("Type of column is not correct", ColumnType.TypeEnum.DAILYCOLUMN, type);
		} catch (ApiException e) {
			fail("Error when getting type of the DailyColumn!" + e.getCode());
		}
		try {
			ColumnType type = api.getColumnType(dailyformulas1.getName());
			assertEquals("Type of column is not correct", ColumnType.TypeEnum.DAILYFORMULA, type);
		} catch (ApiException e) {
			fail("Error when getting type of the DailyFormula!" + e.getCode());
		}
		try {
			ColumnType type = api.getColumnType("LevelXYZ");
			assertEquals("Type of column is not correct", ColumnType.TypeEnum.SALARYLEVEL, type);
		} catch (ApiException e) {
			fail("Error when getting type of the SalaryLevel!" + e.getCode());
		}

		// Columns in use
		try {
			ColumnUse use = api.isColumnInUse(dailycolumn1.getName());
			assertEquals("Column useage is not correct", false, use.isInUse());
		} catch (ApiException e) {
			fail("Error when getting usage of the DailyColumn!");
		}
		try {
			ColumnUse use = api.isColumnInUse(dailyformulas1.getName());
			assertEquals("Column useage is not correct", false, use.isInUse());
		} catch (ApiException e) {
			fail("Error when getting usage of the DailyFormulas!");
		}
		try {
			ColumnUse use = api.isColumnInUse("LevelXYZ");
			assertEquals("Column useage is not correct", false, use.isInUse());
		} catch (ApiException e) {
			fail("Error when getting usage of the SalaryLevel!");
		}

		// Delete columns
		try {
			dailycolumApi.deleteAllDailycolumns();
		} catch (ApiException e) {
			fail("Error when deleting all DailyColumns!");
		}
		try {
			formulaApi.deleteAllDailyformulas();
		} catch (ApiException e) {
			fail("Error when deleting all DailyFormulas!");
		}

	}
}
